# -*- mode: python ; coding: utf-8 -*-
"""
AI Dashboard PyInstaller Spec File

This spec file properly bundles the ai_dashboard package from the src directory.
It handles the src layout and includes all necessary dependencies.

Usage:
    pyinstaller ai-dashboard.spec

Build for different platforms:
    - Windows: pyinstaller ai-dashboard.spec
    - Linux: pyinstaller ai-dashboard.spec
    - macOS: pyinstaller ai-dashboard.spec
"""

import sys
from pathlib import Path

# Get the project root directory
project_root = SPECPATH  # type: ignore[name-defined]
src_dir = Path(project_root) / "src"

# Common hidden imports for dependencies
dependency_imports = [
    # Textual framework - full imports
    "textual",
    "textual.app",
    "textual.binding",
    "textual.color",
    "textual.containers",
    "textual.coordinate",
    "textual.css",
    "textual.css.query",
    "textual.css.styles",
    "textual.dom",
    "textual.driver",
    "textual.events",
    "textual.features",
    "textual.geometry",
    "textual.keys",
    "textual.layout",
    "textual.loop",
    "textual.message",
    "textual.message_pump",
    "textual.messages",
    "textual.pilot",
    "textual.reactive",
    "textual.render",
    "textual.screen",
    "textual.scroll_view",
    "textual.strip",
    "textual.theme",
    "textual.theme_manager",
    "textual.timer",
    "textual.widget",
    "textual.widgets",
    # Textual widgets - specific modules
    "textual.widgets._button",
    "textual.widgets._checkbox",
    "textual.widgets._collapsible",
    "textual.widgets._content_switcher",
    "textual.widgets._data_table",
    "textual.widgets._digits",
    "textual.widgets._directory_tree",
    "textual.widgets._footer",
    "textual.widgets._header",
    "textual.widgets._input",
    "textual.widgets._label",
    "textual.widgets._link",
    "textual.widgets._list_item",
    "textual.widgets._list_view",
    "textual.widgets._loading_indicator",
    "textual.widgets._markdown",
    "textual.widgets._option_list",
    "textual.widgets._placeholder",
    "textual.widgets._pretty",
    "textual.widgets._progress_bar",
    "textual.widgets._radio_button",
    "textual.widgets._radio_set",
    "textual.widgets._select",
    "textual.widgets._sparkline",
    "textual.widgets._static",
    "textual.widgets._switch",
    "textual.widgets._tab_pane",
    "textual.widgets._tabbed_content",
    "textual.widgets._tabs",
    "textual.widgets._text_area",
    "textual.widgets._toast",
    "textual.widgets._toggle_button",
    "textual.widgets._tooltip",
    "textual.widgets._tree",
    "textual.widgets._welcome",
    "textual.widgets._button",
    "textual.widgets.button",
    "textual.widgets.checkbox",
    "textual.widgets.collapsible",
    "textual.widgets.content_switcher",
    "textual.widgets.data_table",
    "textual.widgets.digits",
    "textual.widgets.directory_tree",
    "textual.widgets.footer",
    "textual.widgets.header",
    "textual.widgets.input",
    "textual.widgets.label",
    "textual.widgets.link",
    "textual.widgets.list_item",
    "textual.widgets.list_view",
    "textual.widgets.loading_indicator",
    "textual.widgets.markdown",
    "textual.widgets.option_list",
    "textual.widgets.placeholder",
    "textual.widgets.pretty",
    "textual.widgets.progress_bar",
    "textual.widgets.radio_button",
    "textual.widgets.radio_set",
    "textual.widgets.select",
    "textual.widgets.sparkline",
    "textual.widgets.static",
    "textual.widgets.switch",
    "textual.widgets.tab_pane",
    "textual.widgets.tabbed_content",
    "textual.widgets.tabs",
    "textual.widgets.text_area",
    "textual.widgets.toast",
    "textual.widgets.toggle_button",
    "textual.widgets.tooltip",
    "textual.widgets.tree",
    "textual.widgets.welcome",
    # Rich library
    "rich",
    "rich.console",
    "rich.text",
    "rich.panel",
    "rich.table",
    "rich.progress",
    "rich.style",
    "rich.theme",
    "rich.logging",
    "rich.traceback",
    # Argon2 for password hashing
    "argon2",
    "argon2_cffi",
    "argon2.exceptions",
    "argon2.low_level",
    "argon2.profiles",
    "argon2.backends",
    "argon2.backends._ffi_backend",
    "argon2.backends._hashlib_backend",
    # HTTP clients
    "httpx",
    "httpx._client",
    "httpx._models",
    "httpx._content",
    "httpx._decoders",
    "httpx._exceptions",
    "httpx._status_codes",
    "httpx._types",
    "httpx._urls",
    "aiohttp",
    "aiohttp.client",
    "aiohttp.connector",
    "aiohttp.cookie_jar",
    "aiohttp.formdata",
    "aiohttp.hdrs",
    "aiohttp.helpers",
    "aiohttp.http",
    "aiohttp.payload",
    "aiohttp.reqrep",
    "aiohttp.streams",
    "aiohttp.tcp_helpers",
    "aiohttp.tracing",
    "aiohttp.web",
    # Pydantic
    "pydantic",
    "pydantic.fields",
    "pydantic.main",
    "pydantic.types",
    "pydantic.validators",
    "pydantic.error_wrappers",
    "pydantic_core",
    # Cryptography
    "cryptography",
    "cryptography.fernet",
    "cryptography.hazmat",
    "cryptography.hazmat.primitives",
    "cryptography.hazmat.backends",
    "cryptography.hazmat.backends.default_backend",
    "cryptography.hazmat.primitives.ciphers",
    "cryptography.hazmat.primitives.hashes",
    "cryptography.hazmat.primitives.kdf",
    "cryptography.hazmat.primitives.kdf.pbkdf2",
    # Standard library
    "dataclasses",
    "typing",
    "typing_extensions",
    "pathlib",
    "json",
    "logging",
    "logging.config",
    "logging.handlers",
    "asyncio",
    "asyncio.subprocess",
    "ctypes",
    "ctypes.wintypes",
    "platform",
    "os",
    "sys",
    "io",
    "re",
    "datetime",
    "time",
    "uuid",
    "hashlib",
    "hmac",
    "secrets",
    "base64",
    "binascii",
    "tempfile",
    "contextlib",
    "functools",
    "itertools",
    "collections",
    "enum",
    "copy",
    "abc",
    "warnings",
    "traceback",
    "types",
    "weakref",
    "threading",
    "multiprocessing",
    "concurrent",
    "concurrent.futures",
    # File system
    "watchdog",
    "watchdog.observers",
    "watchdog.events",
    # Markdown
    "markdown_it",
    "mdit_py_plugins",
    "linkify_it",
    "uc_micro",
]

# AI Dashboard modules
ai_dashboard_modules = [
    "ai_dashboard",
    "ai_dashboard.app",
    "ai_dashboard.__main__",
    # Core modules
    "ai_dashboard.core",
    "ai_dashboard.core.config",
    "ai_dashboard.core.exceptions",
    "ai_dashboard.core.logging",
    # Model modules
    "ai_dashboard.models",
    "ai_dashboard.models.agent",
    "ai_dashboard.models.ai_model",
    "ai_dashboard.models.chat",
    "ai_dashboard.models.task",
    "ai_dashboard.models.user",
    # Screen modules
    "ai_dashboard.screens",
    "ai_dashboard.screens.agents",
    "ai_dashboard.screens.chat",
    "ai_dashboard.screens.dashboard",
    "ai_dashboard.screens.login",
    "ai_dashboard.screens.models",
    "ai_dashboard.screens.settings",
    "ai_dashboard.screens.tasks",
    # Service modules
    "ai_dashboard.services",
    "ai_dashboard.services.agent_service",
    "ai_dashboard.services.auth",
    "ai_dashboard.services.model_service",
    "ai_dashboard.services.storage",
    "ai_dashboard.services.task_service",
    # Style modules
    "ai_dashboard.styles",
    "ai_dashboard.styles.theme",
    # Utils modules
    "ai_dashboard.utils",
    "ai_dashboard.utils.formatting",
    "ai_dashboard.utils.helpers",
    "ai_dashboard.utils.validation",
    # Widget modules
    "ai_dashboard.widgets",
    "ai_dashboard.widgets.agent_card",
    "ai_dashboard.widgets.model_card",
    "ai_dashboard.widgets.stat_box",
    "ai_dashboard.widgets.status_indicator",
    "ai_dashboard.widgets.task_item",
]

hidden_imports = dependency_imports + ai_dashboard_modules

a = Analysis(
    ["dashboard.py"],
    pathex=[project_root, str(src_dir)],
    binaries=[],
    datas=[],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "PIL",
        "pytest",
        "mypy",
        "ruff",
        "black",
        "isort",
        "bandit",
        "pylint",
        "IPython",
        "jupyter",
        "notebook",
        "sphinx",
        "docutils",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="ai-dashboard",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Must be True for TUI apps
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
